spring:
  application:
    name: sneivlp-identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Saikumar@0904
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG